print('Hello, world!')
print(5 + 4)
name = input('What is your name?\n')
print('Hi, %s.' % name)
print('Hi, {}.'.format(name))
print(f'Hi, {name}.')
print('Hi, {name}.')
print('Hi, {name}.'.format(name=name))
print('Hi, {name}.'.format(**locals()))
print('Hi, {name}.'.format(**{'name': name}))
print('Hi, {name}.'.format(**vars()))
